//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 06:14:41 PM PDT 
//


package org.hiscox.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="State"/>
 *     &lt;enumeration value="SimilarInsurance"/>
 *     &lt;enumeration value="WrittenContractsUsage"/>
 *     &lt;enumeration value="LargestSourceOfRevenue"/>
 *     &lt;enumeration value="RiskManagementPractices"/>
 *     &lt;enumeration value="OwnershipRightsOfIntellectualPropertyCreated"/>
 *     &lt;enumeration value="ThirdPartyInfringementByIntellectualPropertyCreated"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "code")
@XmlEnum
public enum Code {

    @XmlEnumValue("State")
    STATE("State"),
    @XmlEnumValue("SimilarInsurance")
    SIMILAR_INSURANCE("SimilarInsurance"),
    @XmlEnumValue("WrittenContractsUsage")
    WRITTEN_CONTRACTS_USAGE("WrittenContractsUsage"),
    @XmlEnumValue("LargestSourceOfRevenue")
    LARGEST_SOURCE_OF_REVENUE("LargestSourceOfRevenue"),
    @XmlEnumValue("RiskManagementPractices")
    RISK_MANAGEMENT_PRACTICES("RiskManagementPractices"),
    @XmlEnumValue("OwnershipRightsOfIntellectualPropertyCreated")
    OWNERSHIP_RIGHTS_OF_INTELLECTUAL_PROPERTY_CREATED("OwnershipRightsOfIntellectualPropertyCreated"),
    @XmlEnumValue("ThirdPartyInfringementByIntellectualPropertyCreated")
    THIRD_PARTY_INFRINGEMENT_BY_INTELLECTUAL_PROPERTY_CREATED("ThirdPartyInfringementByIntellectualPropertyCreated");
    private final String value;

    Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Code fromValue(String v) {
        for (Code c: Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
