//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 06:14:41 PM PDT 
//


package org.hiscox.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xyz.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QuoteGenerator_QNAME = new QName("hiscoxQuoteEstimator", "quoteGenerator");
    private final static QName _QuoteGeneratorResponse_QNAME = new QName("hiscoxQuoteEstimator", "quoteGeneratorResponse");
    private final static QName _QuestionsCode_QNAME = new QName("", "code");
    private final static QName _QuestionsResponse_QNAME = new QName("", "response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xyz.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuoteGenerator }
     * 
     */
    public QuoteGenerator createQuoteGenerator() {
        return new QuoteGenerator();
    }

    /**
     * Create an instance of {@link RatePlan }
     * 
     */
    public RatePlan createRatePlan() {
        return new RatePlan();
    }

    /**
     * Create an instance of {@link Monthly }
     * 
     */
    public Monthly createMonthly() {
        return new Monthly();
    }

    /**
     * Create an instance of {@link QuoteGeneratorResponse }
     * 
     */
    public QuoteGeneratorResponse createQuoteGeneratorResponse() {
        return new QuoteGeneratorResponse();
    }

    /**
     * Create an instance of {@link Annual }
     * 
     */
    public Annual createAnnual() {
        return new Annual();
    }

    /**
     * Create an instance of {@link YourPrice }
     * 
     */
    public YourPrice createYourPrice() {
        return new YourPrice();
    }

    /**
     * Create an instance of {@link AboutYourBusiness }
     * 
     */
    public AboutYourBusiness createAboutYourBusiness() {
        return new AboutYourBusiness();
    }

    /**
     * Create an instance of {@link Questions }
     * 
     */
    public Questions createQuestions() {
        return new Questions();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuoteGenerator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "hiscoxQuoteEstimator", name = "quoteGenerator")
    public JAXBElement<QuoteGenerator> createQuoteGenerator(QuoteGenerator value) {
        return new JAXBElement<QuoteGenerator>(_QuoteGenerator_QNAME, QuoteGenerator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuoteGeneratorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "hiscoxQuoteEstimator", name = "quoteGeneratorResponse")
    public JAXBElement<QuoteGeneratorResponse> createQuoteGeneratorResponse(QuoteGeneratorResponse value) {
        return new JAXBElement<QuoteGeneratorResponse>(_QuoteGeneratorResponse_QNAME, QuoteGeneratorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Code }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code", scope = Questions.class)
    public JAXBElement<Code> createQuestionsCode(Code value) {
        return new JAXBElement<Code>(_QuestionsCode_QNAME, Code.class, Questions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "response", scope = Questions.class)
    public JAXBElement<String> createQuestionsResponse(String value) {
        return new JAXBElement<String>(_QuestionsResponse_QNAME, String.class, Questions.class, value);
    }

}
