//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 06:14:41 PM PDT 
//

package org.hiscox.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for quoteGeneratorResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="quoteGeneratorResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="YourPrice" type="{hiscoxQuoteEstimator}yourPrice"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "quoteGeneratorResponse", propOrder = {
    "yourPrice"
})
public class QuoteGeneratorResponse {

    @XmlElement(name = "YourPrice", required = true, nillable = true)
    protected YourPrice yourPrice;

    /**
     * Gets the value of the yourPrice property.
     * 
     * @return
     *     possible object is
     *     {@link YourPrice }
     *     
     */
    public YourPrice getYourPrice() {
        return yourPrice;
    }

    /**
     * Sets the value of the yourPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link YourPrice }
     *     
     */
    public void setYourPrice(YourPrice value) {
        this.yourPrice = value;
    }

}
