//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 06:14:41 PM PDT 
//


package org.hiscox.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for quoteGenerator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="quoteGenerator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AboutYourBusiness" type="{hiscoxQuoteEstimator}aboutYourBusiness"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */




@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "quoteGenerator", propOrder = {
    "aboutYourBusiness"
})
public class QuoteGenerator {

    @XmlElement(name = "AboutYourBusiness", required = true, nillable = true)
    protected AboutYourBusiness aboutYourBusiness;

    /**
     * Gets the value of the aboutYourBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link AboutYourBusiness }
     *     
     */
    public AboutYourBusiness getAboutYourBusiness() {
        return aboutYourBusiness;
    }

    /**
     * Sets the value of the aboutYourBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link AboutYourBusiness }
     *     
     */
    public void setAboutYourBusiness(AboutYourBusiness value) {
        this.aboutYourBusiness = value;
    }

}
