//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.23 at 06:14:41 PM PDT 
//


package org.hiscox.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatePlan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatePlan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QuoteID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Annual" type="{hiscoxQuoteEstimator}Annual"/>
 *         &lt;element name="Monthly" type="{hiscoxQuoteEstimator}Monthly"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatePlan", propOrder = {
    "quoteID",
    "annual",
    "monthly"
})
public class RatePlan {

    @XmlElement(name = "QuoteID", required = true, nillable = true)
    protected String quoteID;
    @XmlElement(name = "Annual", required = true, nillable = true)
    protected Annual annual;
    @XmlElement(name = "Monthly", required = true, nillable = true)
    protected Monthly monthly;

    /**
     * Gets the value of the quoteID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuoteID() {
        return quoteID;
    }

    /**
     * Sets the value of the quoteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuoteID(String value) {
        this.quoteID = value;
    }

    /**
     * Gets the value of the annual property.
     * 
     * @return
     *     possible object is
     *     {@link Annual }
     *     
     */
    public Annual getAnnual() {
        return annual;
    }

    /**
     * Sets the value of the annual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annual }
     *     
     */
    public void setAnnual(Annual value) {
        this.annual = value;
    }

    /**
     * Gets the value of the monthly property.
     * 
     * @return
     *     possible object is
     *     {@link Monthly }
     *     
     */
    public Monthly getMonthly() {
        return monthly;
    }

    /**
     * Sets the value of the monthly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monthly }
     *     
     */
    public void setMonthly(Monthly value) {
        this.monthly = value;
    }

}
